sonar.projectKey=matansuliman_sonarcloud-demo
sonar.organization=matansuliman
sonar.host.url=https://sonarcloud.io

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml